version: "3.7"
services:
  db:
    image: mariadb:10.2.11
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    networks:
      - db
      - service

  users:
    build:
      context: ../users-service
    command: ["sh", "-c", "./scripts/startup.sh root my-secret-pw"]
    networks:
      - service
      - frontend
    expose:
      - 8080
    volumes:
      - ./users/scripts:/scripts
      - liquibase:/semaphore/

  liquibase:
    build:
      context: ../liquibase-scripts
      args:
        LIQUIBASE_TAG: 1.0
    command:
      ["sh", "-c", "./scripts/apply-liquibase-changesets.sh root my-secret-pw"]
    networks:
      - db
    volumes:
      - ./liquibase/scripts:/scripts
      - liquibase:/semaphore/

  proxy:
    build:
      context: ../nginx
    depends_on:
      - users
    networks:
      - frontend
    ports:
      - "9000:80"
    volumes:
      - ./users/nginx-conf/users.conf:/etc/nginx/conf.d/includes/users.conf

networks:
  db:
  service:
  frontend:

volumes:
  liquibase:
